#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
mount -n -t devtmpfs none /dev
dmesg -n 1

clear
. /findcd.sh
. /setenv.sh

if test -z "$CDROM"; then
	echo "Install media / CD-ROM not mounted!"
	cd /
else
	cat welcome
	lunmercy
fi

/bin/sh
