@ECHO OFF
if exist Z:\bzImage.cd goto z
if exist Y:\bzImage.cd goto y
if exist X:\bzImage.cd goto x
if exist W:\bzImage.cd goto w
if exist V:\bzImage.cd goto v
if exist U:\bzImage.cd goto u
if exist T:\bzImage.cd goto t
if exist S:\bzImage.cd goto s
if exist R:\bzImage.cd goto r
if exist Q:\bzImage.cd goto q
if exist P:\bzImage.cd goto p
if exist O:\bzImage.cd goto o
if exist N:\bzImage.cd goto n
if exist M:\bzImage.cd goto m
if exist L:\bzImage.cd goto l
if exist K:\bzImage.cd goto k
if exist J:\bzImage.cd goto j
if exist I:\bzImage.cd goto i
if exist H:\bzImage.cd goto h
if exist G:\bzImage.cd goto g
if exist F:\bzImage.cd goto f
if exist E:\bzImage.cd goto e
if exist D:\bzImage.cd goto d
if exist C:\bzImage.cd goto c

:c
SET CDROM=c:
goto end

:d
SET CDROM=d:
goto end

:e
SET CDROM=e:
goto end

:f
SET CDROM=f:
goto end

:g
SET CDROM=g:
goto end

:h
SET CDROM=h:
goto end

:i
SET CDROM=i:
goto end

:j
SET CDROM=j:
goto end

:k
SET CDROM=k:
goto end

:l
SET CDROM=l:
goto end

:m
SET CDROM=m:
goto end

:n
SET CDROM=n:
goto end

:o
SET CDROM=o:
goto end

:p
SET CDROM=p:
goto end

:q
SET CDROM=q:
goto end

:r
SET CDROM=r:
goto end

:s
SET CDROM=s:
goto end

:t
SET CDROM=t:
goto end

:u
SET CDROM=u:
goto end

:v
SET CDROM=v:
goto end

:w
SET CDROM=w:
goto end

:x
SET CDROM=x:
goto end

:y
SET CDROM=y:
goto end

:z
SET CDROM=z:


:end
