#ifndef LUNMERCY_VERSION_H
#define LUNMERCY_VERSION_H

#define LUNMERCY_VERSION "0.9.7"
#define LUNMERCY_COPYRIGHT "(C) 2024 E. Voirin (oerg866)"
#define LUNMERCY_BACKTITLE "Windows 98 / ME QuickInstall -- v" LUNMERCY_VERSION " " LUNMERCY_COPYRIGHT

#endif 