#ifndef LUNMERCY_VERSION_H
#define LUNMERCY_VERSION_H

#define LUNMERCY_VERSION "0.2.2"
#define LUNMERCY_COPYRIGHT "(C) 2023 Eric Voirin"
#define LUNMERCY_BACKTITLE "Win98SE QuickInstall -- Version " LUNMERCY_VERSION " " LUNMERCY_COPYRIGHT

#endif 